POST  http://localhost:3000/users/signup
content-type: application/json

{
    "email": "email@email.com1",
    "password": "hi"
}

### login

POST  http://localhost:3000/users/login
content-type: application/json

{
    "email": "email@email.com1",
    "password": "hi"
}


### products

GET  http://localhost:3000/products
content-type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjM1ODlmYTQ5LTkwYjQtNDdkMC04ZTgyLWUwZTViYjczZTkyZSIsInVzZXJTdGF0dXMiOiJndWVzdCIsImlhdCI6MTY5MjQ0NzkyMiwiZXhwIjoxNjkyNDQ3OTM3fQ.Amrqx_1bK3PupHGkEmAxaIV3PQ3RPto54FA-dXd9_F4 

{
    "email": "email@email.com1",
    "password": "hi"
}

###  refreshtoken

POST  http://localhost:3000/refreshtoken
content-type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijg0M2FlMGQwLWJjZWUtNDcyYy05NGY0LTJkYTBjM2U3YjhmYiIsInVzZXJTdGF0dXMiOiJndWVzdCIsImlhdCI6MTY5MjQ2MDYzNX0.apDkxO44o5A7Nry3TR2lfcwOUsPYSr0XaBjw4wHp2kw"
}


###  guest

POST  http://localhost:3000/users/login/guest
content-type: application/json






