POST  http://localhost:3000/users/signup
content-type: application/json

{
    "email": "email@email.com1",
    "password": "hi"
}

### login

POST  http://localhost:3000/users/login
content-type: application/json

{
    "email": "email@email.com1",
    "password": "hi"
}


### products

GET  http://localhost:3000/products
content-type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIzMDBmYTRmLWM3M2EtNDg3OS05OTUyLTc4NTMzZjA3MTU2ZSIsImVtYWlsIjoiZW1haWxAZW1haWwuY29tMSIsImZpcnN0bmFtZSI6IiIsImxhc3RuYW1lIjoiIiwicGhvbmUiOiIiLCJpYXQiOjE2OTIzNzg3NTAsImV4cCI6MTY5MjM3ODc2NX0.BJUnNO4sPcrc8BmWOdNc3vGSgloIUDA6OONE7uN1880   

{
    "email": "email@email.com1",
    "password": "hi"
}

###  refreshtoken

POST  http://localhost:3000/refreshtoken
content-type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIzMDBmYTRmLWM3M2EtNDg3OS05OTUyLTc4NTMzZjA3MTU2ZSIsImVtYWlsIjoiZW1haWxAZW1haWwuY29tMSIsImZpcnN0bmFtZSI6IiIsImxhc3RuYW1lIjoiIiwicGhvbmUiOiIiLCJpYXQiOjE2OTIzNzg0Mzd9.Gq2KddHai8Gt1L7V-egg5TwcETRuF4K1sg-3Scy8pag"
}




